import type { Metadata } from "next";
import { Philosopher, Inria_Serif } from "next/font/google";
import "./globals.css";
import "@/styles/utilities.css";
import { ThemeProvider } from "@/hooks/useDarkLightTheme";

const fontHeading = Philosopher({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-heading",
});

const fontBody = Inria_Serif({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  variable: "--font-body",
});
export const metadata: Metadata = {
  title: "Lifeline_Hospital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontHeading.variable} ${fontBody.variable} antialiased`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
